#!/bin/sh
set -e

if [[ $1 != "make" ]]; then
    set -- make "$@"
fi

case $2 in
    -v|--version)
        echo "--> javanile/make.bat <--"
        ;;
    --docker-info)
        set -- docker info
        ;;
    --docker-workdir-ls)
        set -- ls -lah ${PWD}
        ;;
esac

exec "$@"
