#!/bin/sh
set -e

export MAKEBAT_CONTAINER_ID=$(basename $(cat /proc/1/cpuset) | head -c 12)

if [[ $1 != "make" ]]; then
    set -- make "$@"
fi

case $2 in
    -v|--version)
        echo "Make.bat by Francesco Bianco <bianco@javanile.org>"
        ;;
    --docker-info)
        set -- docker info
        ;;
    --docker-version)
        set -- docker version
        ;;
    --docker-compose-version)
        set -- docker-compose version
        ;;
    --docker-workdir-info)
        set -- stat ${PWD}
        ;;
esac

exec "$@"
