#!/bin/sh
set -e

CONTAINER_ID=$(cat /proc/self/cgroup | grep -o -e "docker-.*.scope" | head -n 1 | sed "s/docker-\(.*\).scope/\\1/")

echo "CONTAINER_ID: ${CONTAINER_ID}"		
echo "HOST_PWD: ${HOST_PWD}"

ls /make 

if [[ $1 != "make" ]]; then
    set -- make "$@"
fi

case $2 in
    -v|--version)
        echo "--> javanile/make.bat <--"
        ;;
    --docker-info)
        set -- docker info
        ;;
    --docker-version)
        set -- docker version
        ;;
    --docker-workdir-ls)
        set -- ls -lah ${PWD}
        ;;
    --docker-compose-version)
        set -- docker-compose version
        ;;
    --docker-compose-make)
        set -- cp /opt/.docker-compose-make
        ;;
    --docker-host-pwd)		
		docker container inspect ${CONTAINER_ID}
		set -- true        
		;;
esac

exec "$@"
